### ISSUE TITLE
No difference in wallpaper after running script (Fedora 37)

### ISSUE THREAD

**Issue by dennissherb** [vinceliuice/WhiteSur-wallpapers#3]
Running the script `./install-gnome-backgrounds.sh` does not change the wallpaper 
fedora 37 with gnome 43.4

**Comment by vinceliuice** [comment]
It just install the wallpaper, you need to change the wallpaper in Gnome settings

**Comment by dennissherb** [comment]
Is there no way to have the script change the wallpaper automatically in correspondence with the current time?

**Comment by yaswanthbb** [comment]
> Is there no way to have the script change the wallpaper automatically in correspondence with the current time?

In the Desktop Right Click and Go to "Change Background" and then Select the (WhiteSur Wallpaper or whatever theme u installed) which has time symbol on it
